version: "2"

run:
  timeout: 5m

linters:
  default: all

  settings:
    govet:
      enable-all: true

formatters:
  settings:
    gofmt:
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
        - pattern: "a[b:len(a)]"
          replacement: "a[b:]"
